### ISSUE TITLE
AVbin git error with python arcade under Arch x64

### ISSUE THREAD

**Issue by danboid** [AVbin/AVbin#64]
I'm having trouble getting avbin to work under Arch Linux 64 bit when I build it (and libav) myself from git. I need avbin to use the python arcade library and I need to build it myself as I'm hoping to use it under Arch Linux ARM. Will avbin build on non x86 compatible platforms?

When I install the avbin 10 64 bit Linux binary as downloaded from http://avbin.github.io/ , arcade / pyglet and avbin work fine but when I use my own avbin build, with both libav and avbin being built from the latest git, python dumps errors like this when it tries to use avbin to play a sound:

$ python sprite_bullets.py
Traceback (most recent call last):
  File "sprite_bullets.py", line 147, in <module>
    main()
  File "sprite_bullets.py", line 143, in main
    arcade.run()
  File "/usr/lib/python3.6/site-packages/arcade/window_commands.py", line 203, in run
    pyglet.app.run()
  File "/usr/lib/python3.6/site-packages/pyglet/app/__init__.py", line 143, in run
    event_loop.run()
  File "/usr/lib/python3.6/site-packages/pyglet/app/base.py", line 136, in run
    self._run_estimated()
  File "/usr/lib/python3.6/site-packages/pyglet/app/base.py", line 175, in _run_estimated
    if not platform_event_loop.step(estimate) and estimate != 0.0 and \
  File "/usr/lib/python3.6/site-packages/pyglet/app/xlib.py", line 124, in step
    device.select()
  File "/usr/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 165, in select
    dispatch(e)
  File "/usr/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 900, in dispatch_platform_event_view
    event_handler(e)
  File "/usr/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 1212, in _event_button
    x, y, button, modifiers)
  File "/usr/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1154, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/usr/lib/python3.6/site-packages/pyglet/event.py", line 365, in dispatch_event
    if getattr(self, event_type)(*args):
  File "sprite_bullets.py", line 94, in on_mouse_press
    arcade.sound.play_sound(self.gun_sound)
  File "/usr/lib/python3.6/site-packages/arcade/sound.py", line 79, in play_sound
    sound.play()
  File "/usr/lib/python3.6/site-packages/pyglet/media/__init__.py", line 472, in play
    player.queue(self)
  File "/usr/lib/python3.6/site-packages/pyglet/media/__init__.py", line 978, in queue
    group.queue(source)
  File "/usr/lib/python3.6/site-packages/pyglet/media/__init__.py", line 695, in queue
    source = source._get_queue_source()
  File "/usr/lib/python3.6/site-packages/pyglet/media/__init__.py", line 622, in _get_queue_source
    return StaticMemorySource(self._data, self.audio_format)
AttributeError: 'StaticSource' object has no attribute '_data'

Maybe there is a config option for libav and/or avbin that I need to enable to get avbin to work with pyglet and arcade?

Thanks

**Comment by danboid** [comment]
Here's the PKGBUILD I'm using to build avbin:

# Maintainer: Christopher Arndt <aur -at- chrisarndt -dot- de>

pkgname=avbin
pkgver=11
pkgrel=1
_gittag="$pkgname-$pkgver"
_gitsubmodule="https://github.com/AVbin/libav.git"
pkgdesc="Cross-platform media decoding library"
arch=('i686' 'x86_64')
url="http://avbin.github.com/"
license=('LGPL')
depends=('bzip2' 'zlib')
conflicts=('avbin7')
makedepends=('git' 'yasm')
options=('!makeflags')
# The build script relies on being run in a git checkout,
# the downloadable release tarball doesn't work with it
source=("${pkgname}::git+https://github.com/AVbin/AVbin.git")
sha256sums=('SKIP')

prepare() {
    cd "${srcdir}/${pkgname}"

    if [ ! -e libav/Makefile ]; then
        git rm libav
        git submodule add --force ${_gitsubmodule} libav
    fi

    git checkout
    cd libav
    git checkout
}

build() {
    cd "${srcdir}/${pkgname}"

    target="linux-$(echo $CARCH | sed -e 's/_/-/')"
    msg "Building target ${target}..."
    # Linux Makefile uses LDFLAGS directly for ld command line
    export LDFLAGS="$(echo $LDFLAGS | sed -e 's/^-Wl,//')"
    bash -x build.sh --fast ${target}
}

package() {
    cd "${srcdir}/${pkgname}"

    target="linux-$(echo $CARCH | sed -e 's/_/-/')"
    install -dm755 "$pkgdir/usr/lib"
    install -m644 "dist/${target}/libavbin.so.${pkgver}" "$pkgdir/usr/lib"
    ln -sf "libavbin.so.${pkgver}" "$pkgdir/usr/lib/libavbin.so"
}

**Comment by danboid** [comment]
BTW $LDFLAGS is not set on my machine so you can ignore that bit

**Comment by danboid** [comment]
```
$ python --version
Python 3.6.0
$ ffmpeg --version
ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.2.1 (GCC) 20160830
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Unrecognized option '-version'.
Error splitting the argument list: Option not found
$ gcc --version
gcc (GCC) 6.2.1 20160830
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
